name: jar build
description: springboot jar build
inputs:
  secrets:
    required: true
    description: 'Secrets toJSON'

runs:
  using: composite
  steps:
  - uses: graalvm/setup-graalvm@v1
    with:
      version: 'latest'
      java-version: '21'
      components: 'native-image'
      cache: 'maven'
      github-token: ${{ fromJSON(inputs.secrets).GITHUB_TOKEN }}
      native-image-job-reports: 'true'
  
  - run: |
      mkdir -p ~/.m2
      touch ~/.m2/settings.xml
      
      cat > ~/.m2/settings.xml <<EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>github</id>
              <username>$USER</username>
              <password>$GITHUB_TOKEN</password>
            </server>
          </servers>
        </settings>
      EOF
    env:
      USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ fromJSON(inputs.secrets).GITHUB_TOKEN }}

  - name: Publish maven artifact to GitHub Packages
    run: |
      ./mvnw -B clean install
  
  - name: Publish maven artifact to GitHub Packages
    run: |
      #./mvnw -B native:compile
      ./mvnw -B build-helper:parse-version versions:set -DnewVersion=1.0.${{ github.run_number }}
      ./mvnw -B deploy
    env:
      GITHUB_TOKEN: ${{ fromJSON(inputs.secrets).GITHUB_TOKEN }}

  - name: Github Release
    run: gh release create v1.0.${{github.run_number}} ./target/*.jar
    env:
      GH_TOKEN: ${{ fromJSON(inputs.secrets).GITHUB_TOKEN }}